&PED_TIPPED='+PED_TIPPED+'\
&PED_NUMPED='+PED_NUMPED+'\
&PED_CIUDAD='+PED_CIUDAD+'\
&PED_CEDULA='+PED_CEDULA+'\
&PED_CEDCON='+PED_CEDCON+'\
&PED_FECPED='+PED_FECPED+'\
&PED_FECINI='+PED_FECINI+'\
&PED_FECVEN='+PED_FECVEN+'\
&PED_ORDCOM='+PED_ORDCOM+'\
&PED_AGENTE='+PED_AGENTE+'\
&PED_DESPP='+PED_DESPP+'\
&PED_DESPF='+PED_DESPF+'\
&PED_PLAZO='+PED_PLAZO+'\
&PED_VENDED='+PED_VENDED+'\
&PED_TIPCLI='+PED_TIPCLI+'\
&PED_LISPRE='+PED_LISPRE+'\
&PED_TIPCTA='+PED_TIPCTA+'\
&PED_TIPNOT='+PED_TIPNOT+'\
&PED_VALFLE='+PED_VALFLE+'\
&PED_VALSEG='+PED_VALSEG+'\
&PED_TASARM='+PED_TASARM+'\
&PED_MONEDA='+PED_MONEDA+'\
&PED_BODEGA='+PED_BODEGA+'\
&PED_ALMCON='+PED_ALMCON+'\
&PED_CODSEC='+PED_CODSEC+'\
&PED_CODTRA='+PED_CODTRA+'\
&PED_OBSERV='+PED_OBSERV+'\
&PED_OBSADI='+PED_OBSADI+'\
&PED_DIRENV='+PED_DIRENV+'\
&PED_ESTREG='+PED_ESTREG+'\
&PED_ACTIVO='+PED_ACTIVO+'\
&PED_CIERRE='+PED_CIERRE+'\
&PED_ESTADO='+PED_ESTADO+'\
&PED_COPIAS='+PED_COPIAS+'\
&PED_NOMEMP='+PED_NOMEMP+'\
&PED_VERSIO='+PED_VERSIO+'\
&PED_EQUIPO='+PED_EQUIPO+'\
&PED_CODOPE='+PED_CODOPE+'\
&PED_FECOPE='+PED_FECOPE+'\
&PED_USUARIO='+PED_USUARIO+'\
&PED_PROREG='+PED_PROREG+'\
&PED_SECTOR='+PED_SECTOR+'\
&PED_NUMREQ='+PED_NUMREQ+'\
&PED_TIPREQ='+PED_TIPREQ+'\
&PED_TIPOPE='+PED_TIPOPE+'\
&PED_CEDREF='+PED_CEDREF+'\
&PED_NUMEVE='+PED_NUMEVE+'\
&PED_VALPED='+PED_VALPED+'\
&PED_TIPINV='+PED_TIPINV+'\
&PED_PREFIJ='+PED_PREFIJ+'\
&PED_OBSINT='+PED_OBSINT+'\
&PED_FECAUT='+PED_FECAUT+'\
&PED_PORIMP='+PED_PORIMP+'\
&PED_PORADM='+PED_PORADM+'\
&PED_CODCLI='+PED_CODCLI+'\
&PED_FECENT='+PED_FECENT+'\
&PED_CONENT='+PED_CONENT+'\
&PED_TIPANT='+PED_TIPANT+'\
&PED_PREANT='+PED_PREANT+'\
&PED_NUMANT='+PED_NUMANT+'\
&PED_FECANT='+PED_FECANT+'\
&PED_VALANT='+PED_VALANT+'\
&PED_AUTCOS='+PED_AUTCOS+'\
&PED_CONREQ='+PED_CONREQ+'\
&PED_SOLANT='+PED_SOLANT+'\
&PED_FECCOS='+PED_FECCOS+'\
&PED_USUCOS='+PED_USUCOS+'\
&PED_USUSOL='+PED_USUSOL+'\
&PED_FECSOL='+PED_FECSOL+'\
&PED_NUMCON='+PED_NUMCON+'\
&PED_CONPRO='+PED_CONPRO+'\
&PED_FECORD='+PED_FECORD+'\
&PED_CODICA='+PED_CODICA+'




























